version: '3'
services:
  my-redis:
    container_name: redis-container
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  my-lb4:
    container_name: lb4-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:5
    environment:
      - REDIS_HOST=my-redis
    env_file:
      - .env.production
    ports:
      - '80:8000'
    depends_on:
      - my-redis
