version: '3'
services:
  my-redis:
    container_name: redis-container
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  my-socket:
    container_name: socket-container
    build:
      context: ./ps-server-socket
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
